apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-test-w1
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: jobtest
        image: takuyak/kubectl:v1.19.0
        command: ['sh', '-c', 'sleep 60 && kubectl --kubeconfig /tmp/config delete pod nginx']
        volumeMounts:
        - name: kubeconfig
          mountPath: "/tmp/"
          readOnly: true
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: kubeconfig
        secret:
          secretName: secret-kubeconfig
