apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-test-w2
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
      - name: jobtest
        image: busybox
        command: ['sh', '-c', 'sleep 60']
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: regcred
